before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
language: ruby
cache: bundler
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: VWNlZKF9NWLIPjXIhNiD3o69XS2z588FeK4g/Y3tpb7G8YGA/cZdc1f+OHl5X3A0CD0sowsZwDYxj2+bjeiQzQDeVVv+jnZlMtIAQBZS71ZIGuFeH0xdYHw3RiLbBVokXUCGuMosIjxDu6OZ2Vs1P6cWtyzdrCsHbdAH6E32AqS4rfVCIDBZKhhN9Vjh64Eiyw3MIudtw7Vu1bccWcojw4IlcDEMCQP2CypRoT8PVYfLUYAtnc+S3cSFKjFQbTNUw3c5rsp2gbLGZ1Bq+R3+3NicDP4OZ7YWCKNi80gkiEejCd6v4+wFUE4U5Z8+ZustS9799PPfmNgqGqIAImwsg1L+WZDErWDz6T0bdmDnHI0jJHGpiOfoT5aDRpi7cZtYIJG3BT5ad7a8DrkpDltv9g9sSyOXZY35bbvNYqY8/gOFnYrQWlymX/UjkKOTlYMlBaWDhHLModS3OJnZaxDrNoLE03Qn8Oyz1X/55TWG1EboMS+E+OgFTOdOEFbdsE+B3/AY9tWsKzCFmcr/wOsXbf56fOU2OD2OmFF1tNOcKXzD/8+8TRTriz+K9lTY+b1tvTt51kWI2QzGH717u6LAEMDc55fdHUGVL/JzO/MUYXXKrZ6cQ99m2Dls8k/s/YQ1HLU0axznIJ7Jz46sf3gBp6k8jVrii92XMtCl40IOANA=
  app: pet-stagram
  run: rake db:migrate
  on:
    repo: tomasdoh/petstagram
    branch: master
  skip_cleanup: true
